# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jekyll admin
email: gusquinalha@gmail.com
description: "jekyll admin"
baseurl: "/jekyll-admin"
url: ""
twitter_username: gustavoquinalha
github_username:  gustavoquinalha

# Build settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins_dir:
  - jekyll-admin

sass:
  style: compressed